# Configuración de Gradle para OrbBlaze
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# SOLUCIÓN PARA CRASH EN PRODUCCIÓN (Android 10/13)
# Desactivamos el R8 Full Mode que es demasiado agresivo con Compose
android.enableR8.fullMode=false
